### ISSUE TITLE
WIFI Slow

### ISSUE THREAD

**Issue by wtfmate79** [Olaren15/t490s-oc-files#2]
Wifi only getting 40MBPS, is there a kext fix or do I need a better wifi card?

**Comment by Olaren15** [comment]
This is a limitation of the [itlwm kext](https://openintelwireless.github.io/itlwm/FAQ.html#performance-sucks). It is the only kext that will currently work with intel wifi.

**Comment by wtfmate79** [comment]
> This is a limitation of the [itlwm kext](https://openintelwireless.github.io/itlwm/FAQ.html#performance-sucks). It is the only kext that will currently work with intel wifi.

Yes I read that too. Is it possible to use USB wifi adapter or change the internal one?
